name: CI

on: 
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.14]
        otp: [25.0]

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Get Deps Cache
      uses: actions/cache@v3
      id: cache-deps
      with:
        path: deps/
        key: ${{hashFiles('mix.lock')}}-deps

    - name: Get Build Cache
      uses: actions/cache@v3
      with:
        path: _build/
        key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-${{hashFiles('mix.lock')}}-build

    - name: Get PLT Cache
      uses: actions/cache@v2
      with:
        path: priv/plts
        key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-${{hashFiles('mix.lock')}}-plt

    - name: Get deps
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Compile
      run: mix compile --warnings-as-errors

    - name: Check Credo
      run: mix credo --strict

    - name: Check Format
      run: mix format --check-formatted

    - name: Check Tests
      run: mix test

    - name: Check Dialyzer
      run: mix dialyzer
